# Generated by Django 5.1.6 on 2025-02-14 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_course_time_create_course_time_update_and_more"),
        ("users", "0002_remove_user_token_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата оплаты")),
                ("payment_amount", models.FloatField(blank=True, null=True, verbose_name="Сумма оплаты")),
                (
                    "payment_methods",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(0, "Наличные"), (1, "Перевод на счёт")],
                        null=True,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "payment_status",
                    models.SmallIntegerField(
                        choices=[(0, "Ожидает оплаты"), (1, "Оплачен")], default=0, verbose_name="Статус оплаты"
                    ),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="lms.course",
                        verbose_name="оплаченный курс",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="lms.lesson",
                        verbose_name="оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
