# Generated by Django 5.1.6 on 2025-02-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите страну проживания",
                max_length=20,
                null=True,
                verbose_name="Страна проживания",
            ),
        ),
    ]
