# Generated by Django 5.1.6 on 2025-03-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_link_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_methods",
            field=models.CharField(
                choices=[("cash", "Оплата наличными"), ("transfer", "Перевод на счёт")],
                default="transfer",
                help_text="Выберете метод оплаты",
                max_length=8,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Ожидает оплаты"), ("paid", "Оплачен"), ("failed", "Ошибка оплаты")],
                default="pending",
                help_text="Выберете статус оплаты",
                max_length=8,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
