# Generated by Django 5.1.6 on 2025-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_lesson_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="time_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="time_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
